export const SENTENCES = [
  "The quick brown fox jumps over the lazy dog.",
  "A silent wind moves across the empty field.",
  "Bright stars shimmer above the quiet town.",
  "The old clock ticks in the dark hallway.",
  "A sudden rain falls on the dusty road.",
  "The small cat sleeps on the warm chair.",
  "Fresh coffee fills the morning air.",
  "The red kite dances in the blue sky.",
  "A distant train echoes through the valley.",
  "The young artist paints a vivid dream.",
  "Soft waves touch the sandy shore.",
  "The tall trees sway in the gentle breeze.",
  "A curious child opens the hidden door.",
  "The golden sun rises over the hills.",
  "A lonely bird sings at dawn.",
  "The busy market hums with life.",
  "A bright candle flickers in the window.",
  "The calm river flows toward the sea.",
  "A brave knight guards the ancient gate.",
  "The silver moon lights the path ahead.",
  "A shy smile appears on her face.",
  "The cold snow covers the silent street.",
  "A quick thought crosses his mind.",
  "The deep forest hides many secrets.",
  "A warm fire crackles in the hearth.",
  "The sharp wind cuts through the night.",
  "A simple song lifts her spirit.",
  "The heavy door closes with a thud.",
  "A narrow path leads to the village.",
  "The clear lake reflects the bright sky.",
  "A gentle rain taps on the roof.",
  "The proud mountain stands against the clouds.",
  "A tiny spark starts a great fire.",
  "The quiet library smells of old books.",
  "A soft blanket warms the child.",
  "The dark tunnel stretches into silence.",
  "A bright idea changes everything.",
  "The restless crowd waits for news.",
  "A slow river bends around the rocks.",
  "The empty bench faces the sea.",
  "A distant thunder rolls across the plains.",
  "The friendly dog wags its tail.",
  "A thin mist covers the meadow.",
  "The broken fence leans to one side.",
  "A careful hand writes a short note.",
  "The loud bell rings at noon.",
  "A lonely road winds through the hills.",
  "The blue ocean sparkles in sunlight.",
  "A bright leaf falls to the ground.",
  "The steady drum beats in the distance.",
  "A hidden garden blooms behind the wall.",
  "The patient teacher explains the lesson.",
  "A small boat drifts on the lake.",
  "The silent night feels endless.",
  "A sharp whistle breaks the calm air.",
  "The brave explorer maps the island.",
  "A cold breeze enters the room.",
  "The shining armor gleams in battle.",
  "A faint shadow moves along the wall.",
  "The eager crowd cheers loudly.",
  "A warm smile greets the guest.",
  "The narrow bridge shakes slightly.",
  "A sudden laugh fills the room.",
  "The tall grass hides the path.",
  "A bright star guides the traveler.",
  "The simple meal tastes delicious.",
  "A heavy storm approaches quickly.",
  "The green valley stretches for miles.",
  "A soft whisper echoes in the cave.",
  "The wooden table stands firm.",
  "A quick glance reveals the truth.",
  "The peaceful garden invites reflection.",
  "A thin line divides the page.",
  "The quiet lake mirrors the trees.",
  "A bold plan forms overnight.",
  "The steady rain soaks the ground.",
  "A bright flash lights the sky.",
  "The smooth stone feels cool.",
  "A gentle voice calls his name.",
  "The lonely tower rises above the fog.",
  "A small flame burns steadily.",
  "The crisp air smells of pine.",
  "A brave heart faces fear.",
  "The silent clock marks each second.",
  "A distant light flickers softly.",
  "The proud flag waves high.",
  "A hidden message lies within.",
  "The warm sand covers her feet.",
  "A sharp turn surprises the driver.",
  "The clear path leads forward.",
  "A sudden change shifts the mood.",
  "The dark clouds gather slowly.",
  "A soft laugh breaks the silence.",
  "The bright room feels welcoming.",
  "A careful step avoids danger.",
  "The small town rests quietly.",
  "A faint glow appears at dawn.",
  "The tall building touches the sky.",
  "A simple question demands thought.",
  "The quiet forest feels alive.",
  "The calm sea stretches endlessly.",
  "A thin cloud drifts overhead.",
  "The old bridge creaks softly.",
  "A bright flower blooms nearby.",
  "The distant mountain looks blue.",
  "A soft pillow supports her head.",
  "The narrow street feels crowded.",
  "A sudden breeze cools the air.",
  "The empty room echoes loudly.",
  "A quick smile changes the mood.",
  "The bright lantern guides the way.",
  "A silent promise lingers.",
  "The green fields shine after rain.",
  "A steady hand draws a circle.",
  "The low hum fills the hall.",
  "A simple truth stands firm.",
  "The dark night hides the stars.",
  "A gentle touch calms him.",
  "The quiet path invites a walk.",
  "A bold voice speaks clearly.",
  "The smooth surface reflects light.",
  "A sharp crack splits the wood.",
  "The golden light fades slowly.",
  "A soft breeze lifts her hair.",
  "The narrow window frames the sky.",
  "A quick decision saves time.",
  "The calm morning feels fresh.",
  "A hidden door opens silently.",
  "The bright horizon promises hope.",
  "A lonely star shines above.",
  "The warm tea soothes the throat.",
  "A distant echo answers back.",
  "The tall cliff overlooks the sea.",
  "A soft knock sounds twice.",
  "The clear stream runs swiftly.",
  "A bright spark ignites excitement.",
  "The small bird hops along.",
  "A heavy book rests on the desk.",
  "The silent hall stands empty.",
  "A bold step changes fate.",
  "The cool shade offers relief.",
  "A gentle rain refreshes the earth.",
  "The quiet meadow feels peaceful.",
  "A sharp eye notices detail.",
  "The warm light fills the room.",
  "A narrow path twists ahead.",
  "The bright moon glows softly.",
  "A simple plan works well.",
  "The calm wind slows down.",
  "A sudden noise startles him.",
  "The long road stretches forward.",
  "A bright idea sparks action.",
  "The quiet village sleeps soundly.",
  "A gentle wave rolls ashore.",
  "The dark cave feels cold.",
  "A soft melody drifts by.",
  "The clear sky looks endless.",
  "A small hope remains.",
  "The proud lion stands tall.",
  "A thin branch snaps easily.",
  "The warm breeze feels pleasant.",
  "A sudden flash blinds him.",
  "The silent lake rests still.",
  "A careful word avoids conflict.",
  "The bright garden smells sweet.",
  "A lonely traveler walks on.",
  "The sharp blade cuts cleanly.",
  "A gentle glow fills the room.",
  "The calm rhythm slows down.",
  "A small stone skips twice.",
  "The clear voice rings out.",
  "A bold dream inspires change.",
  "The dark forest grows quiet.",
  "A soft echo fades away.",
  "The tall tower casts a shadow.",
  "A simple smile brings comfort.",
  "The bright sun warms the earth.",
  "A sudden gust shakes the leaves.",
  "The quiet harbor feels safe.",
  "A thin ribbon ties the gift.",
  "The calm lake reflects clouds.",
  "A gentle sigh escapes her lips.",
  "The old tree stands firm.",
  "A bright spark lights hope.",
  "The narrow road curves sharply.",
  "A silent prayer fills the heart.",
  "The cool night feels peaceful.",
  "A small bell rings softly.",
  "The clear water tastes fresh.",
  "A bold choice changes everything.",
  "The bright sky clears slowly.",
  "A sudden chill runs down his spine.",
  "The quiet room feels calm.",
  "A gentle breeze moves the curtain.",
  "The dark sky hints at rain.",
  "A soft glow lights the path.",
  "The tall grass sways gently.",
  "A quick step closes the gap.",
  "The warm sun feels comforting.",
  "A distant horn sounds twice.",
  "The calm forest smells fresh.",
  "A small cloud floats by.",
  "The bright window frames the sunrise.",
  "A sharp turn leads home.",
  "The silent field stretches wide.",
  "A gentle ripple moves outward.",
  "The dark water hides depth.",
  "A bold laugh fills the hall.",
  "The clear tone sounds pure.",
  "A sudden spark catches fire.",
  "The quiet air feels heavy.",
  "A thin shadow crosses the floor.",
  "The bright star fades slowly.",
  "A soft wind cools the skin.",
  "The narrow gate stands open.",
  "A simple task takes time.",
  "The calm voice reassures her.",
  "A distant drum beats steadily.",
  "The dark cloud passes quickly.",
  "A bright flame burns high.",
  "The quiet trail leads uphill.",
  "A gentle wave touches shore.",
  "The clear bell rings again.",
  "A small smile appears briefly.",
  "The warm room feels cozy.",
  "A sudden shift changes direction.",
  "The tall trees block the wind.",
  "A soft light glows within.",
  "The narrow shelf holds books.",
  "A bold move surprises them.",
  "The calm sea looks endless.",
  "A gentle breeze carries scent.",
  "The dark road feels long.",
  "A bright beam cuts through fog.",
  "The quiet house stands alone.",
  "A simple answer solves it.",
  "The warm fire burns bright.",
  "A sudden whisper breaks silence.",
  "The clear sky shines blue.",
  "A small boat rocks gently.",
  "The calm tide rises slowly.",
  "A thin thread holds tight.",
  "The bright spark fades away.",
  "A soft hum fills space.",
  "The narrow path climbs upward.",
  "A bold voice calls out.",
  "The quiet dawn feels hopeful.",
  "A gentle smile lingers.",
  "The dark woods seem endless.",
  "A bright star twinkles above.",
  "The calm breeze moves softly.",
  "A sudden knock startles her.",
  "The clear stream glistens brightly.",
  "A small light shines ahead.",
  "The warm glow comforts him.",
  "A thin veil covers the sky.",
  "The bright sun sets slowly.",
  "A soft rain begins to fall.",
  "The narrow door creaks open.",
  "A bold step moves forward.",
  "The quiet street lies empty.",
  "A gentle touch feels kind.",
  "The dark shadow stretches long.",
  "A bright flash lights the night.",
  "The calm river bends quietly.",
  "A small spark remains alive.",
  "The warm wind drifts past.",
  "A sudden cry breaks out.",
  "The clear horizon looks distant.",
  "A soft glow surrounds them.",
  "The narrow tunnel feels tight.",
  "A bold plan takes shape.",
  "The quiet breeze fades away.",
  "A gentle ripple crosses water.",
  "The dark sky clears at last.",
  "A bright dawn begins anew.",
  "The calm earth rests still.",
  "A small hope grows stronger.",
  "The warm sunlight fills the valley.",
  "A sudden storm ends quickly.",
  "The clear path shines ahead.",
  "A soft whisper returns softly.",
  "The narrow lane twists sharply.",
  "A bold spirit never quits.",
  "The quiet lake reflects stars.",
  "A gentle laugh echoes lightly.",
  "The dark forest feels deep.",
  "A bright future awaits them.",
  "The calm waters settle slowly.",
  "A small dream takes flight.",
  "The warm night feels endless.",
  "A sudden flash fades fast.",
  "The clear morning brings peace.",
  "A soft wind brushes past.",
  "The narrow bridge stands strong.",
  "A bold heart beats steadily.",
  "The quiet sky turns pink.",
  "A gentle light appears.",
  "The dark night fades away.",
  "A bright day begins now."
];
