export const moreSentenceTemplates: string[] = [
  "in the absence of {{nouns}}, the {{noun}} becomes {{an_adjective}} {{noun}}",
  "every {{adjective}} {{noun}} conceals {{a_noun}} within its {{noun}}",
  "{{a_noun}} beneath the {{noun}} is often {{an_adjective}} {{noun}}",
  "to call {{a_noun}} {{an_adjective}} is to mistake it for {{a_noun}}",
  "the {{noun}} that follows {{a_noun}} is rarely {{an_adjective}} {{noun}}",
  "within {{nouns}}, we discover {{an_adjective}} {{nouns}}",
  "no {{noun}} remains {{adjective}} when touched by {{nouns}}",
  "{{a_noun}} among {{nouns}} appears almost {{an_adjective}}",
  "the {{adjective}} {{noun}} trembles like {{a_noun}} in {{nouns}}",
  "each {{noun}} hides {{a_noun}} shaped by {{an_adjective}} {{nouns}}",
  "{{a_noun}} becomes {{an_adjective}} {{noun}} through {{nouns}}",
  "the {{noun}} of the {{noun}} is merely {{a_noun}}",
  "behind every {{adjective}} {{noun}} lies {{a_noun}} of {{nouns}}",
  "{{nouns}} transform the {{noun}} into {{an_adjective}} {{noun}}",
  "a {{noun}} without {{a_noun}} risks becoming {{an_adjective}}",
  "the {{adjective}} {{nouns}} drift toward {{an_adjective}} {{nouns}}",
  "{{a_noun}} inside {{a_noun}} forms {{an_adjective}} {{noun}}",
  "where {{nouns}} gather, {{an_adjective}} {{nouns}} emerge",
  "the {{noun}} rests upon {{a_noun}} of {{adjective}} {{nouns}}",
  "{{a_noun}} reflects the {{adjective}} {{noun}} it surrounds",
  "in time, {{nouns}} resemble {{an_adjective}} {{nouns}}",
  "{{a_noun}} carries {{a_noun}} through {{adjective}} {{nouns}}",
  "the {{adjective}} {{noun}} collapses into {{a_noun}}",
  "without {{adjective}} {{nouns}}, {{nouns}} seem {{adjective}}",
  "the {{noun}} becomes {{a_noun}} before it becomes {{an_adjective}}",
  "{{an_adjective}} {{noun}} echoes across {{nouns}}",
  "each {{adjective}} {{noun}} invites {{a_noun}}",
  "{{a_noun}} defines the {{adjective}} {{noun}}",
  "beyond {{nouns}}, there is only {{an_adjective}} {{noun}}",
  "the {{noun}} within {{a_noun}} remains {{an_adjective}}",
  "{{a_noun}} under {{nouns}} appears {{adjective}}",
  "the {{adjective}} {{noun}} seeks {{a_noun}} in {{nouns}}",
  "every {{noun}} requires {{a_noun}} of {{adjective}} {{nouns}}",
  "{{nouns}} conceal {{an_adjective}} {{noun}}",
  "the {{noun}} after {{nouns}} feels {{an_adjective}}",
  "{{a_noun}} becomes the {{noun}} of {{adjective}} {{nouns}}",
  "through {{nouns}}, the {{noun}} turns {{adjective}}",
  "no {{adjective}} {{noun}} survives without {{nouns}}",
  "{{a_noun}} among {{adjective}} {{nouns}} grows {{adjective}}",
  "the {{noun}} before {{a_noun}} was {{an_adjective}}",
  "{{nouns}} shape {{a_noun}} into {{an_adjective}} {{noun}}",
  "an excess of {{nouns}} creates {{an_adjective}} {{nouns}}",
  "{{a_noun}} balances the {{adjective}} {{noun}}",
  "the {{adjective}} {{noun}} leans toward {{a_noun}}",
  "{{a_noun}} without {{a_noun}} is merely {{a_noun}}",
  "the {{noun}} beyond {{nouns}} is {{an_adjective}} {{noun}}",
  "{{an_adjective}} {{noun}} defines {{nouns}}",
  "{{nouns}} remember {{an_adjective}} {{nouns}}",
  "the {{adjective}} {{noun}} surrounds {{a_noun}}",
  "{{a_noun}} from {{nouns}} becomes {{an_adjective}} {{noun}}",
  "each {{noun}} mirrors {{a_noun}}",
  "the {{adjective}} {{noun}} dissolves into {{nouns}}",
  "{{a_noun}} of {{adjective}} {{nouns}} remains {{an_adjective}}",
  "within the {{noun}}, {{nouns}} appear {{adjective}}",
  "{{a_noun}} marks the {{noun}} as {{an_adjective}}",
  "the {{noun}} beside {{a_noun}} feels {{adjective}}",
  "{{nouns}} give birth to {{an_adjective}} {{nouns}}",
  "{{a_noun}} becomes {{a_noun}} beneath {{nouns}}",
  "the {{adjective}} {{noun}} shelters {{a_noun}}",
  "without {{nouns}}, {{a_noun}} seems {{an_adjective}}",
  "{{an_adjective}} {{noun}} surrounds the {{adjective}} {{noun}}",
  "each {{noun}} is touched by {{a_noun}}",
  "{{a_noun}} renders the {{noun}} {{adjective}}",
  "the {{noun}} between {{nouns}} is {{an_adjective}}",
  "{{nouns}} disturb the {{adjective}} {{noun}}",
  "{{a_noun}} shapes {{nouns}} into {{adjective}} {{nouns}}",
  "the {{adjective}} {{noun}} frames {{a_noun}}",
  "{{a_noun}} guides the {{noun}} through {{nouns}}",
  "the {{noun}} beyond {{a_noun}} becomes {{an_adjective}}",
  "{{an_adjective}} {{noun}} holds {{a_noun}}",
  "each {{adjective}} {{noun}} births {{a_noun}}",
  "{{nouns}} awaken {{an_adjective}} {{nouns}}",
  "the {{noun}} against {{nouns}} appears {{adjective}}",
  "{{a_noun}} crowns the {{adjective}} {{noun}}",
  "the {{adjective}} {{noun}} consumes {{a_noun}}",
  "{{a_noun}} crosses {{nouns}} as {{an_adjective}} {{noun}}",
  "no {{noun}} escapes {{adjective}} {{nouns}}",
  "{{nouns}} gather around {{a_noun}}",
  "the {{noun}} shaped by {{nouns}} grows {{adjective}}",
  "{{a_noun}} beneath {{an_adjective}} {{noun}} lingers",
  "the {{adjective}} {{noun}} questions {{a_noun}}",
  "{{a_noun}} within {{nouns}} becomes {{adjective}}",
  "{{an_adjective}} {{noun}} surrounds {{nouns}}",
  "each {{noun}} follows {{a_noun}} into {{nouns}}",
  "{{a_noun}} anchors the {{adjective}} {{noun}}",
  "the {{noun}} after {{a_noun}} feels {{an_adjective}}",
  "{{nouns}} define the {{adjective}} {{noun}}",
  "{{a_noun}} tests the {{noun}} against {{nouns}}",
  "the {{adjective}} {{noun}} seeks {{an_adjective}} {{noun}}",
  "{{a_noun}} echoes through {{adjective}} {{nouns}}",
  "without {{a_noun}}, the {{noun}} is {{an_adjective}}",
  "{{nouns}} scatter before {{an_adjective}} {{noun}}",
  "the {{noun}} touched by {{a_noun}} turns {{adjective}}",
  "{{a_noun}} opens the {{noun}} to {{nouns}}",
  "each {{adjective}} {{noun}} conceals {{an_adjective}} {{noun}}",
  "{{nouns}} cradle {{a_noun}}",
  "the {{noun}} within {{nouns}} remains {{adjective}}",
  "{{a_noun}} alters the {{adjective}} {{noun}} forever"
];
